### ISSUE TITLE
Arch Linux packaging?

### ISSUE THREAD

**Issue by mxmilkb** [Spaghettis/Spaghettis#230]
What absolute path should the tcl/ directory have on a full system installation?

I've added Spaghettis to the AUR but it is an incomplete install right now https://aur.archlinux.org/packages/spaghettis-git

**Comment by nicolasdanet** [comment]
Spaghettis is (for now) work-in-progress and such it could be deceptive for an user to consider it stable.
It changes every day! Anything could be removed without any care for backward compatibility.
That's why this software is explicitly "compile-by-yourself" only.  Moreover it is NOT installed to let people try without fears and damages. It has not been tested a lot. That should be done before to release a tagged version. Currently it is not enough mature to be packaged.

In the future i was thinking about to use a more general way to handle packaging.
See: #21
But if somebody wants to maintain a specific package it could be great also. In that case i should read deeply the Arch Linux packaging guidelines first.

BTW it doesn't need fftw, nor portaudio dependencies (i'm not sure for others e.g. hicolor-icon-theme).

**Comment by nicolasdanet** [comment]
To respond to your question, this is how it WAS installed by default:

```
/usr/local/bin/spaghettis
/usr/local/include/m_spaghettis.h
/usr/local/lib/spaghettis/tcl/*.tcl
/usr/local/lib/spaghettis/help/*.pdhelp
```

https://github.com/Spaghettis/Spaghettis/blob/cfb8ceb65615ae0a83c6c105824edc94cce6a5cf/src/makefile.linux#L13

But it is not used anymore and it is not good for Arch Linux!

**Comment by mxmilkb** [comment]
That's fair enough, I've added a note of "(in development, alpha)" to the description.

The AUR has the [largest availability](https://repology.org/repositories/statistics/total) of software packages of any distro, and it's on the AUR entry maintainer to resolve any problems that might arise in time with a package, be it binary, tarball or VCS based. Other users can flag an AUR entry as being out-of-date, and if it was broken my system update would fail.

I updated the PKGBUILD, now `spaghettis` launches from path. Thanks for your help :)

**Comment by nicolasdanet** [comment]
First, thanks for your work and your feedback.

Do you need to update the package each time i push a change?
Is it automatically fetch from the GitHub repository?
I'll try to not break things, but how can i notify you if i add/change dependencies for instance? 

The build.sh script launches the test suite also. It is probably not a good idea now. It makes  the process longer (on Raspbian a bunch of minutes). I'll probably remove the tests from this script and add another one only for whom who want to give a try.

**Comment by mxmilkb** [comment]
If a new dependency is required but not added to the PKGBUILD, either I don't have it and my build will fail, or someone else won't and they'll hopefully leave a comment on the AUR entry. Or if you want to ping me in this thread, or if you wish, you could be a maintainer of the PKGBUILD entry, it's done via Git and SSH key via the AUR site.

If you think the tests aren't worth adding atm, I'll not add them for now.

**Comment by nicolasdanet** [comment]
Ok thanks, i'll have a look to the AUR site. Concerning the tests you have nothing to do. I'll make the change on the Spaghettis repository side!

**Comment by nicolasdanet** [comment]
@mxmilkb 

I installed Manjaro Linux on a computer and  i checked the PKGBUILD.

I did few changes in order to match more the packaging policy.

< https://github.com/nicolasdanet/T/blob/master/miscellaneous/PKGBUILD > 

[PKGBUILD.txt](https://github.com/Spaghettis/Spaghettis/files/4152528/PKGBUILD.txt)

I get results above passing the namcap tool.

```
[jojo@jojo-pc Package]$ namcap PKGBUILD
[jojo@jojo-pc Package]$ namcap spaghettis-git-r5441.75a6d3a1-1-x86_64.pkg.tar.xz
spaghettis-git W: ELF file ('usr/bin/spaghettis') lacks FULL RELRO, check LDFLAGS.
```
I didn't fix the FULL RELRO warning as it implies benchmarks and tests that i don't want to do now.

**Comment by nicolasdanet** [comment]
@mxmilkb bump (is that notifications work)?
