### ISSUE TITLE
"canvas: unknown method declare/vis" with Automatonism patches

### ISSUE THREAD

**Issue by mxmilkb** [Spaghettis/Spaghettis#235]
When trying out the [Automatonism](https://www.automatonism.com/) modular synth patches, I'm getting the output;

```
canvas: unknown method declare
spaghettis: can't make [ declare -path patch_editor_abs ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty empty -2 -8 0 10 -158136 -262144 -1 0 1 ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty empty -2 -8 0 10 -150893 -1 -1 0 1 ]
spaghettis: can't make [ vline~ ]
spaghettis: can't make [ vline~ ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty empty -2 -8 0 10 -262144 -1 -1 0 1 ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty empty -2 -8 0 10 -158136 -262144 -1 0 1 ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty empty -2 -8 0 10 -150893 -1 -1 0 1 ]
spaghettis: can't make [ vline~ ]
spaghettis: can't make [ vline~ ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty empty -2 -8 0 10 -262144 -1 -1 0 1 ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty 0-127 -2 -8 0 10 -262144 -1 -1 0 1 ]
spaghettis: can't make [ hsl 128 15 0 127 0 0 empty empty 0-127 -2 -8 0 10 -262144 -1 -1 0 1 ]
canvas: unknown method vis
audio: invalid samplerate
dsp: JACK ports / 2 channels
dsp: JACK ports / 2 channels
dsp: 44100 Hz
dsp: stop
```

Are these Pd features from after the Spaghettis fork, or are they features Spaghettis is moving away from?

**To reproduce**
Get Automatonism, rename main.pd, load in Spaghettis.

**Screenshots**
![spag_pd_errors](https://user-images.githubusercontent.com/108225/73283694-696b9680-41eb-11ea-8b30-cbbd47283910.png)

**Comment by nicolasdanet** [comment]
Yes, it is features that Spaghettis is intentionally moving away from.

- There is no declare object anymore (now file path is handle +/- ala Max/MSP).
- Sliders can be created only with full names (hslider/vslider).
- Vline~ has been removed (in profit of line~) since control and the DSP are not interleaved. 
- IIRC vis method (renamed) is private.

Spaghettis is almost compatible with Pd vanilla, but with time it is less and less.
I doubt that any patch on the web can be opened without an error message!
They often contains unbelievable hacks, strange workarounds, or old features. 
I aim to make a brand new software without immoderate respect to it roots. 
It the opposite of the libpd or Purr Data approach.

Of course, all the changes i made should be documented. #220
But TBH i'm motivated only into development now.
It appears that i failed to obtain a large support from the Pd community.
That's probably why with time, i throw compatibility i kept at first.
It is less conservative. #233 #234
I don't want anymore to restrain my work for an unlikely user.

The best way to test and explore that project is to go across the examples provided.
They should work ;-)

< https://github.com/Spaghettis/Tools >

Thanks for your interest!

**Comment by nicolasdanet** [comment]
Note that to get the DSP working, Spaghettis must be run at the same sample rate than JACK. 

1. Run JACK at 44100 Hz.
2. Change the preference file of Spaghettis to match JACK server. 

Preference file on GNU/Linux is at <  $HOME/.config/spaghettis/preferences.txt >.
I mostly tested at 44100 Hz, but it should work at others.
