### ISSUE TITLE
Create binaries for testing?

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#253]
It might be interesting to publish some binaries for those who are interested in at least testing out the current limited capabilities of Spaghettis? I tried to build for my system (MacOS 10.15) and whenever opening the app there were many errors.

This would definitely be a milestone to reach for, but I think it would be worthwhile to gains some visibility. Perhaps making it stable enough to run some benchmarks of the multi-threading capabilities? I think that would be enough!

**Comment by nicolasdanet** [comment]
I don't want to provide binaries since it is more work while i really need less work. Spaghettis is supposed to work well on macOS 10.15 ; it is supposed to be stable! I didn't tested that master branch since monthes and i'll do it ASAP. But if it doesn't work that's an issue. What kind of errors to you have?

**Comment by nicolasdanet** [comment]
I have quickly tested the build script on my system 10.15.7 and it fails to build the Wish app. Tcl/TK is a nightmare. It is always broken at each OS update.

**Comment by nicolasdanet** [comment]
If i use the Tcl/Tk "core-8.6-branch" instead of the "release" tag, it compiles fine. Then I don't get any errors opening the Spaghettis app.

**Comment by nicolasdanet** [comment]
I have quickly tested the build script on my system 10.15.7 and it fails to build the Wish app. Tcl/Tk is a nightmare. It is always broken at each macOS update (even minors). If i use the Tcl/Tk core-8.6-branch instead of the release tag, it compiles fine. Note that then i don't get any errors opening the Spaghettis app.

**Comment by nicolasdanet** [comment]
You can reopen an issue if it doesn't work fine with the fix i'll push soon. #254
