### ISSUE TITLE
Support for standard shortcuts for native objects and functions

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#260]
Many of the objects cannot be created with the standard Pd shortcuts. Is there any plan to implement this?
I also noticed that the shortcut to run the DSP does not work.

**Comment by nicolasdanet** [comment]
Spaghettis do not use the Pd shortcuts but others. If you open the menus, you can see the shortcuts used.
There's a lot of things that are not the same as Pd. I don't want to be forced to follow Pd (since i forked it to change it)!
With time, the work to develop Spaghettis and to backport Pd features would be impossible.
For Pd users i admit that is a bit painful. But at start I decided to design Spaghettis as a brand new software (whitout to respect Pd). Most of time i think that the Pd community is too much conservative. Here it should be exactly the contrary.

**Comment by nicolasdanet** [comment]
Notice that due to a bug of how Tk handle shortcuts on macOS, you can see the shortcuts for creating objects (cmd-1, cmd-2, ....) only with the RIGHT-CLICK menu. Does the shortcut works for you? It is always buggy with all the keyboard and system available. For instance: < https://forum.pdpatchrepo.info/topic/11738/spaghettis-yet-another-fork-of-pure-data/19 >.

**Comment by nicolasdanet** [comment]
@jacksonmgoode Can you confirm that the shortcuts work (or not)?

**Comment by jacksonmgoode** [comment]
Yes, they do. The shortcuts listed in the right-click menu work well. The way they appear in fixed placement from the moment the shortcut is pressed is another oddity, but maybe that should be a separate feature request.

Still, the DSP toggle does not work (it would be helpful to have some visual indication if the DSP was turned on/off within the console header).

**Comment by nicolasdanet** [comment]
> Still, the DSP toggle does not work.

You mean that (Shift + Cmd + R) doesn't trigger the DSP on/off?

**Comment by jacksonmgoode** [comment]
Yes, that shortcut does not toggle using Shift + Cmd + R.

**Comment by nicolasdanet** [comment]
Key binding is very annoying with Tk/Wish. 
You have the same OS as me, thus i guess it is the computer/keyboard that is not the same.
In that case i don't see why the keyboard would be a problem.
Surely something to change (again) in that file <  https://github.com/Spaghettis/Spaghettis/blob/master/tcl/ui_bind.tcl#L63 >. 
What's your level in programming?  :wink:

**Comment by jacksonmgoode** [comment]
1. Mostly, non-C related languages (Python, JS, Web, Matlab, etc.)
2. Curiously, Save As does work, but not of the other modifiers work (Send to front/back, DSP). However, enabling Caps-Lock allows me to use all of the shortcuts. I think <Shift-$mod-Key-r> should be <Shift-$mod-Key-R>.

**Comment by nicolasdanet** [comment]
>I think <Shift-$mod-Key-r> should be <Shift-$mod-Key-R>.

I think so. On my old macbook it i not the case. I don't know why. I'll have a try with both binding.

**Comment by nicolasdanet** [comment]
But as usual it is NOT so easy. It is triggered twice with that modification.
I think that now as reported in a post above the menu behavior as changed.
I need more investigations.

**Comment by nicolasdanet** [comment]
IMHO, Wish doesn't handle properly the shortcuts with the shift key on your computer (except Save As).

As a workaround:

1. I'll remove the shortcuts for bring/front.
2. I'll use another one for DSP (the same as Pd if possible or just Cmd + R).

I already spent weeks to make that things work on all platform in the past...

**Comment by jacksonmgoode** [comment]
Maybe this is better left until you decide to switch away from Tk.

**Comment by nicolasdanet** [comment]
>Maybe this is better left until you decide to switch away from Tk.

It should be best for my sanity, but as the same time i HATE to let something broken.
I thanks you to rise those bugs.
With the workaround above it should be OK, with the bonus that it will have less shortcuts, thus less bugs in the future.

**Comment by nicolasdanet** [comment]
@jacksonmgoode Could you test that? I removed the Shift Key from the buggy shortcuts.

**Comment by jacksonmgoode** [comment]
Looks good!
