### ISSUE TITLE
A vision for the future

### ISSUE THREAD

**Issue by jacksonmgoode** [Spaghettis/Spaghettis#261]
Just curious what your vision is in terms of shifts _away_ from Pure Data - in design, concept, programmatically or otherwise?

I think this is an important point for this project and would be nice to be included in the readme, as I'm sure people will wonder how this fork differs from other forks of Pd.

**Comment by nicolasdanet** [comment]
There was a list of issues that i tought to be explicit about the futur of Spaghettis. I recently closed them, but are still fetchable with the "archived" label. I know that the documentation should be improved. But frankly, anybody know what are the problems with Pure Data (GUI design, DSP locks, ...). But since it is over complicated to change, everybody seems to be blind about that, and claims that everything is ok! That fork is just an attempt to make Pd works. Anyway your request is valid. I'll spend time later to improve the README.

**Comment by nicolasdanet** [comment]
Note that since i'll change a lot of things with the new GUI, i'm always reluctant to make documentation that will be wrong in the future. Problem with FLOSS is always to manage the limited time available for a project.

**Comment by nicolasdanet** [comment]
I reopened archived issues into the Roadmap milestone.

**Comment by nicolasdanet** [comment]
After reflexions and to avoid to do it twice, i'll do it later.
Anyway i'm pretty sure no user of Pd will use that fork at this point (even with more documentation). 
And TBH i"m a bit tired with all that unsuccessful self promotion!

See: #220

**Comment by jacksonmgoode** [comment]
I see - I just think if there was a more clear explanation about the project on GitHub at least, it would garner attention. I'm sure there are folks that are looking for a modern platform that carries some of the concepts of Pd.

**Comment by nicolasdanet** [comment]
I think you are right.
But at the same time wihtout the GUI rewrite that project isn't really modern. ;-)
I'll add a short text in the next days to explain the rationale about that fork.
Anyway thanks for your interest!
